In [1]:
from __future__ import print_function
import torch

In [8]:
torch.cuda.is_available() # check GPU did not spaz out

True

c-style random values in unitialised memory

In [9]:
x = torch.empty(5, 3)
print(x)
x = torch.rand(5, 3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 1.8788e+31],
        [1.7220e+22, 5.9018e-10, 8.5036e+20],
        [1.0187e-11, 1.0812e-05, 8.3090e-10],
        [1.0430e-08, 8.1256e+20, 2.0774e+20],
        [8.4113e+20, 3.1369e+27, 7.0800e+31]])
tensor([[0.9217, 0.3537, 0.5862],
        [0.7403, 0.1280, 0.8890],
        [0.4866, 0.2441, 0.0879],
        [0.7629, 0.3855, 0.8221],
        [0.7575, 0.2490, 0.8704]])


make tensor from tensor keeps size the same

.size() returns normal tuple

In [17]:
print(torch.randn_like(torch.ones(5, 3)))
print(torch.ones(5,3).size())

tensor([[ 0.6911, -0.7647, -0.7327],
        [ 1.2840,  0.2016,  0.2367],
        [ 1.4114,  2.7817,  0.3715],
        [ 0.9186,  0.7406,  0.2175],
        [-0.8408,  0.4175, -0.3297]])
torch.Size([5, 3])


arithmetic has inplace and normal versions

In [24]:
x = torch.ones(5, 3)
y = torch.rand(5, 3)
print(x + y)
x.add_(y)
print(x)
print(x[:, 1]) # select middle column with python indexing

tensor([[1.4495, 1.7141, 1.2684],
        [1.4854, 1.7018, 1.9967],
        [1.4050, 1.5406, 1.4306],
        [1.2036, 1.3555, 1.8164],
        [1.6319, 1.3772, 1.2500]])
tensor([[1.4495, 1.7141, 1.2684],
        [1.4854, 1.7018, 1.9967],
        [1.4050, 1.5406, 1.4306],
        [1.2036, 1.3555, 1.8164],
        [1.6319, 1.3772, 1.2500]])
tensor([1.7141, 1.7018, 1.5406, 1.3555, 1.3772])


.view reshapes tensor, -1 infers size for given dimension

In [32]:
x = torch.rand(4, 4)
print(x.view(-1, 8)) # (2, 8)
print(x.view(2, 2, -1)) # (2, 2, 4)

tensor([[0.2145, 0.7067, 0.2251, 0.7972, 0.1904, 0.0440, 0.0234, 0.1883],
        [0.2889, 0.1281, 0.7873, 0.0774, 0.2588, 0.3558, 0.1669, 0.0792]])
tensor([[[0.2145, 0.7067, 0.2251, 0.7972],
         [0.1904, 0.0440, 0.0234, 0.1883]],

        [[0.2889, 0.1281, 0.7873, 0.0774],
         [0.2588, 0.3558, 0.1669, 0.0792]]])


 send tensor to gpu

In [35]:
cuda = torch.device('cuda')
x = x.to(cuda)
y = torch.ones_like(x, device=cuda) # create on gpu
print(x + y)

tensor([[1.2145, 1.7067, 1.2251, 1.7972],
        [1.1904, 1.0440, 1.0234, 1.1883],
        [1.2889, 1.1281, 1.7873, 1.0774],
        [1.2588, 1.3558, 1.1669, 1.0792]], device='cuda:0')
